"""Write docs/digits.js from zipsolve/digits.npz so the web page uses the same templates."""

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
data = np.load(ROOT / "zipsolve" / "digits.npz")
templates = {k: [round(float(v), 3) for v in data[k].ravel()] for k in sorted(data.files)}
out = ROOT / "docs" / "digits.js"
out.write_text("// Generated by tools/export_templates.py: do not edit.\n"
               f"const DIGIT_TEMPLATES = {json.dumps(templates, separators=(',', ':'))};\n"
               "if (typeof module !== 'undefined') module.exports = DIGIT_TEMPLATES;\n")
print(f"wrote {out}")
